### ISSUE TITLE
Tanıtım eksik

### ISSUE THREAD

**Issue by huseyinkozan** [ozguryazilimas/telve4#1]
Selam,

Arama motorunu kullanmadan Telve'nin ne olduğunu anlayamadım. Şu sayfadaki bilgileri eklemek veya sayfaya bağlantı vermek faydalı olabilir : 
https://ozguryazilim.com.tr/urunlerimiz/telve-java-ee-framework/

**Comment by Arimao** [comment]
readme.md dosyasi guncellendi. Feedback icin tesekkur ederiz.
